apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patch-rolling.yml
  target:
    group: argoproj.io
    kind: Rollout
    version: v1alpha1

images:
- name: adservice
  newName: gcr.io/fishing-313318/adservice
  newTag: 6dfb4a2
- name: cartservice
  newName: gcr.io/fishing-313318/cartservice
  newTag: 6dfb4a2
- name: checkoutservice
  newName: gcr.io/fishing-313318/checkoutservice
  newTag: 6dfb4a2
- name: currencyservice
  newName: gcr.io/fishing-313318/currencyservice
  newTag: 6dfb4a2
- name: emailservice
  newName: gcr.io/fishing-313318/emailservice
  newTag: 6dfb4a2
- name: frontend
  newName: gcr.io/fishing-313318/frontend
  newTag: 6dfb4a2
- name: paymentservice
  newName: gcr.io/fishing-313318/paymentservice
  newTag: 6dfb4a2
- name: productcatalogservice
  newName: gcr.io/fishing-313318/productcatalogservice
  newTag: 6dfb4a2
- name: recommendationservice
  newName: gcr.io/fishing-313318/recommendationservice
  newTag: 6dfb4a2
- name: redis
  newName: redis
  newTag: 5.0.7-alpine3.11
- name: shippingservice
  newName: gcr.io/fishing-313318/shippingservice
  newTag: 6dfb4a2
